version: '3.5'

services:

  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
networks:

  elk:
    driver: bridge
